name: Postman Collection Workflow

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: '30 02 * * *'  # 8am IST everyday
    - cron: '00 14 * * *'  # 7:30pm IST everyday
    - cron: '00 06 * * 1-5'  # 11:30am IST, Monday to Friday

jobs:
  run-postman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4.2.2

      - name: Install Nodejs and npm
        uses: gacts/setup-node-with-cache@v1.2.2
        with:
          node-version: '22'

      - name: Install Newman and HTML Extra Reporter
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Run the Postman collection with Newman
        run: | 
          newman run "Inwarranty-flow Collection.postman_collection.json" \
            -e QA.postman_environment.json \
            -r cli,htmlextra \
            --reporter-htmlextra-export newman/index.html

      - name: Newman Report
        if: always() # ensure that the archive executed irrespective whether the prev step has passed or not
        uses: actions/upload-artifact@v4.3.1
        with:
          name: Newman Report
          path: newman/*.html

      - name: Creating github page branch
        if: always()
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: newman/
